version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - run:
          name: Install AWS CDK via NPM
          command: |
            npm i aws-cdk
      - run:
          name: Verify CDK installed
          command: |
            npx cdk --help
