version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - run:
          name: Install AWS CDK via NPM
          command: |
            npm i -g aws-cdk
      - run:
          name: Verify CDK installed
          command: |
            which cdk
            cdk --help
